#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d UwU OwO 7u7

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#AutoStart applications
sxhkd &
picom --config ~/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
setxkbmap -layout latam &
